services:
  - type: web
    name: ludo-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        fromDatabase:
          name: ludo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ludo-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: ludo-db
          property: database
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: ludo-db
    plan: free
